### ISSUE TITLE
Neuron model for network creation

### ISSUE THREAD

**Issue by Rionzagal** [Rionzagal/BioSig-evaluation#1]
# Overview:
The model representing the Izhikevich equations and parameters must be represented in a class in order to organize and access all of its data and possible actions. Knowing that the network will contain any number of neurons, and each may have different behaviors and different parameters, it is important to represent each neuron as its own entity, and be able to extract its possible behaviors.

# TASKS:
- [x] Create a Neuron class to represent the neuron model stated by Izhikevich with its corresponding attributes
- [x] Add a database of different parameters and neuron types in a separate file, in case more types are created afterwards
- [x] Generate the methods calculate_step and activate, which return the neuron key values calculated by each step and a response obtained over a certain period of time
- [x] Generate a NeuronTypes enumerator to limit the options of the types to be input in each neuron in order to avoid non-valid or non-existent types
